# Site settings
title: 
email: your-email@domain.com
baseurl: "/1988" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
description: "서울 강남의 중심, 청담동에 위치한 신축빌딩 청담1988은<br>프리미엄과 실용성을 모두 갖춘 공간을 제공합니다."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#f1f1f1'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: 네이버 지도
    url: https://m.place.naver.com/share?id=1098490023&tabsPath=%2Fhome&appMode=detail
  - title: 카카오 지도
    url: https://place.map.kakao.com/m/1853586279

# Build settings
markdown: kramdown
permalink: pretty